### PR TITLE
Add button in slider block

### PR DESCRIPTION
**Pull request by iRohitSingh**
Screenshot 2023-06-23 at 16 24 34

### CODE REVIEW

**Comment by sneridagh** [comment]
@iRohitSingh what if we do not want a button in the slider?
Please make it optional, maybe a boolean?

**Comment by iRohitSingh** [comment]
ok

**Comment by iRohitSingh** [comment]
https://github.com/kitconcept/volto-slider-block/assets/61353484/d35020a8-e2ad-4ed1-8548-160543d0673a

**Comment by sneridagh** [comment]
@iRohitSingh please implement the changes I asked you via meet. Using the vanilla Volto from the docker environment.

image

**Comment by iRohitSingh** [comment]
@sneridagh fixed.

Screenshot

Screenshot 2023-07-26 at 19 18 35

**Comment by danalvrz** [comment]
@iRohitSingh It is looking very nice, just a couple responsiveness related details:

- Desktop view and edit, image width is off:
Screenshot 2023-07-27 at 8 49 58
Screenshot 2023-07-27 at 10 48 52


- Tablet (810px), Slider not displayed correctly:
Screenshot 2023-07-27 at 8 53 42

- Mobile, Slider not displayed correctly:
Screenshot 2023-07-27 at 8 51 52

**Comment by iRohitSingh** [comment]
https://github.com/kitconcept/volto-slider-block/assets/61353484/d976fb09-6fb3-40ac-93ff-a1f40e5b2304

**Comment by iRohitSingh** [comment]
@sneridagh @davisagli I am struggling with a problem :
1. login as editor  
2.Then check the responsiveness 
- you notice that when the scree is between 769px to 849px we are not able to see slider block .(without login it work fine)
-  I also find the style of width also show wrong when screen is between 769px to 849px

Screenshot 2023-07-28 at 15 33 11


Can you please help me in that ?

Every thing works fine except that.

**Comment by davisagli** [comment]
Closing this, we'll implement it in volto-light-theme instead to avoid a breaking change here.

**Pull request closed without merging**
